let titleList = [
"The Book of Common Law",
"Carnivorous Gardening",
"The Book of Twelve Seasons",
"A Journey Beyond the Veil",
"Raising Weasels With Confidence",
"A Short History of Dwarves",
"What Color Is Your Dragon?",
"Samwell’s Guide to Arms and Armor",
"The Silent Bard and Other Myths",
"The Letters of Saint Cuthbert",
"Secret Doors and Passages (bad poetry collection)",
"A Journeyman’s Guide to Barrel Making",
"Basic Carpentry For Complex Dungeons",
"The Great Extraplanar Hoax",
"Fungal Crop Rotation For Underground Dwellers",
"How To Use a Sundial In the Rain",
"Farming Wheat, Barley, and Giant Frogs",
"A Caretaker’s Guide to Giant Centipedes",
"101 Untraceable Poisons",
"All Giants Great and Small",
"50 Things To Do With a Dead Lich",
"Beauty Is In the Eyes of the Beholder",
"Planning Your Castle Construction",
"Tavern Management In Rural Areas",
"Accidental Pickpocketing and Other Excuses",
"Spells We Are Still Trying To Make Work",
"Samwell’s Guide To Wands",
"The Legend of Tucker’s Kobolds",
"Potatoes That Resemble Goblins: A Pictorial",
"Vines: Small, Medium, Giant",
"Defeating a Heavy Iron Gate",
"Counting to Ten for Orcs",
"The Arrow of Benevolent Intent",
"Monstrous Philosophies",
"Thirty Ways To Skin a Dragon",
"Warlock vs Sorcerer: How To Spot the Difference",
"Tower Defenses, What Works and What Does Not",
"Samwell’s Guide To Holy Symbols",
"Prayers For the Righteous",
"Identifying Grubs, Worms, and Sentient Fungi",
"Wyverns, Wyrms, Drakes & Dragons: The Differences",
"Recipes For Disaster: A Cookbook",
"A Field Guide To Fey",
"1001 Things To Do Underground",
"A History of Thieve Guilds",
"Weather Manipulation and Farm Management",
"The Whole Hollow World Atlas",
"The Great Bird Hoax",
"What’s Behind That Door? A Listener’s Handbook",
"Turnips. The Gods’ Own Gift To the World",
"How To Make a Lantern Out Of a Skull",
"Candlemaking for Clerics",
"Surveillance Techniques That Don’t Work",
"The Myth of the Useful Bard",
"Samwell’s Guide To Useless Glyphs",
"Thieves Cant… or Can They?",
"Hunting Mushrooms In the Dark",
"Cursed Idols and Relics of the Desert",
"Climate Change During the Dark Wizard Times",
"Airships. An Inflatable History",
"How To Live Forever—or Close To It",
"Giant Flowers. Friend or Foe?",
"The Most Grand Illusion",
"Daily Affirmations for Tyrants",
"Hidden Staircases and Secret Doors",
"Managing Your Giant Vines",
"How To Get Way With Murder",
"Poisoned Pens. Allegory or Literal Danger?",
"Sonnets for Sorcerers",
"Seven Knights For Seven Dragons",
"River Navigation Through Magical Forests",
"A Biological Survey of Gnomish “People”",
"Mysterious Structures That Glow",
"Samwell’s Guide To Blue-Colored Potions",
"The Unlikely Romance of Owls and Bears",
"Rocks That Sort of Look Like Orcs",
"Animal Husbandry and Midwifery",
"Castle Gardens For Long Sieges",
"How Green Is My Goblin?",
"How To Tell a Brew Is True",
"Cubicles & Commuters: A Fantasy Roleplaying Guide",
"Explosive Grass and Other Lawn Care Tips",
"Is Your Spouse a Polymorph? 50 Signs They Might Be",
"Plots, Intrigue, and Politics",
"The Book of Uncommon Law",
"A Simple Guide To Vampires",
"Unwrapping the Mystery of Mummies",
"Ghost Stories Written By Ghosts",
"Samwell’s Guide To Love and Love Potions",
"The Underground Horoscope",
"Orienteering Without a Compass",
"How To Work a Sextant",
"Fabled Treasures and Monsters",
"Puppetry For Evil and Parties",
]

let authorList = [
"William Shakespeare",
"Emily Dickinson",
"H. P. Lovecraft",
"Arthur Conan Doyle",
"Leo Tolstoy",
"Edgar Allan Poe",
"Robert Ervin Howard",
"Rabindranath Tagore",
"Rudyard Kipling",
"Seneca",
"John Donne",
"Sarah Williams",
"Oscar Wilde",
"Catullus",
"Alfred Tennyson",
"William Blake",
"Charles Dickens",
"John Keats",
"Theodor Herzl",
"Percy Bysshe Shelley",
"Ernest Hemingway",
"Barack Obama",
"Anton Chekhov",
"Henry Wadsworth Longfellow",
"Arthur Schopenhauer",
"Jacob De Haas",
"George Gordon Byron",
"Jack London",
"Robert Frost",
"Abraham Lincoln",
"O. Henry",
"Ovid",
"Robert Louis Stevenson",
"John Masefield",
"James Joyce",
"Clark Ashton Smith",
"Aristotle",
"William Wordsworth",
"Jane Austen",
"Niccolò Machiavelli",
"Lewis Carroll",
"Robert Burns",
"Edgar Rice Burroughs",
"Plato",
"John Milton",
"Ralph Waldo Emerson",
"Margaret Thatcher",
"Sylvie d'Avigdor",
"Marcus Tullius Cicero",
"Banjo Paterson",
"Woodrow Wilson",
"Walt Whitman",
"Theodore Roosevelt",
"Agatha Christie",
"Ambrose Bierce",
"Nikola Tesla",
"Franz Kafka",
]

const randomTitle = function() {
    return titleList[Math.floor(Math.random() * titleList.length)]
}

const randomAuthor = function() {
    return authorList[Math.floor(Math.random() * authorList.length)]
}
export {randomTitle, randomAuthor}